#include <iostream>

using namespace std;

int main()
{
    string characterName = "John";
    int characterAge;
    characterAge = 35;
    cout << "Bismillah!"<< endl;
    cout << "There was a man named " << characterName << endl;
    cout << "He was " << characterAge << " years old"<<endl;
    cout << "He liked the name "<< characterName << endl;
    cout << "But he didn't like the age "<<  characterAge <<endl;
    return 0;
}
